apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mlops
  template:
    metadata:
      labels:
        app: mlops
    spec:
      containers:
        - name: mlops
          image: shamailkhan/weather-prediction-project:latest
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: mlops-service
spec:
  type: NodePort
  selector:
    app: mlops
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30001
