
name: Run Test Cases

on:
  pull_request:
    branches: [ test ]
  push:
    branches: [ test ]

jobs:
  run-tests:
    name: Run Tests on test.py
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run test.py
        run: |
          python test.py
